### ISSUE TITLE
VSCode extension of slidev dosen't work

### ISSUE THREAD

**Issue by sensuikan1973** [sensuikan1973/flutter-expensive-native-embedding-journey#8]
- https://github.com/slidevjs/slidev-vscode/issues/16
- https://github.com/slidevjs/slidev-vscode/issues/15

**Comment by sensuikan1973** [comment]
I can see preview with localhost serving (`npm run dev`).
So, priority of this issue is minor.

**Comment by ctstewart** [comment]
Why was this closed? I don't see a solution to the problem with the extension.

Are you implying that the extension is deprecated? If that's the case, why doesn't it say that anywhere?
